### ISSUE TITLE
Variable example Insert error 

### ISSUE THREAD

**Issue by TeguhTeknisi** [Syafiqlim/ESP32_MySQL#2]
Hi,
Thanks for the Library,
Why when using Variable_Insert_ESP32MySQL.ino , i got insert error
But using Basic_Insert_ESP32MySQL i can insert 

i try to modify the code to

    String INSERT_SQL1 = String("INSERT INTO ") + default_database + "." + default_table 
                 + " (" + pH_column + ") VALUES ('" + pHValue + "'";
    ESP32_MYSQL_DISPLAY(INSERT_SQL1);
    
    // Execute the query
    if ( !query_mem.execute(INSERT_SQL1.c_str()) )
    {
      ESP32_MYSQL_DISPLAY("Insert 1 error");
    }
    else
    {
      ESP32_MYSQL_DISPLAY("Data 1 Inserted.");
    }

    String INSERT_SQL2 = String("INSERT INTO ") + default_database + "." + default_table 
                 + " (" + temp_column + ") VALUES ('" + temp + "'";
    ESP32_MYSQL_DISPLAY(INSERT_SQL2);
    
    // Execute the query
    if ( !query_mem.execute(INSERT_SQL2.c_str()) )
    {
      ESP32_MYSQL_DISPLAY("Insert 2 error");
    }
    else
    {
      ESP32_MYSQL_DISPLAY("Data 2 Inserted.");
    }

but the data will not one line
| 5.30       | NULL     | 
| NULL        | 35.00    |
+-------------+----------+

Please help. Thanks

**Comment by Syafiqlim** [comment]
Sorry for late reply since I'm currently doing my internship. I have solved the issue and updated the example to v1.0.1 of library, where missing "," and + symbols in the syntax of query. The data inserted not in one line because you have 2 queries, resulting the data are inserted in different queries thus different rows.
